version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - gosimple
    - revive
    - gocyclo
    - misspell
    - bodyclose
    - unconvert
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      severity: warning

issues:
  exclude-dirs:
    - modules/organization/infrastructure/grpc/proto
  exclude-rules:
    - path: _test\.go$
      linters:
        - gocyclo
        - errcheck
    - path: modules/organization/infrastructure/grpc/proto/
      linters:
        - govet
        - staticcheck
        - errcheck
        - ineffassign
        - unused
        - gocritic
        - gosimple
        - revive
        - gocyclo
        - misspell
        - bodyclose
        - unconvert
