/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'block-library': BlockLibrary;
    pages: Page;
    posts: Post;
    plans: Plan;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    landing: Landing;
    'pricing-page': PricingPage;
    navbar: Navbar;
    footer: Footer;
    theme: Theme;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
    'pricing-page': PricingPageSelect<false> | PricingPageSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  blocks?:
    | (
        | {
            eyebrowBadge?: string | null;
            eyebrowText?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            trustLine?: string | null;
            image?: (number | null) | Media;
            dashboardAlerts?:
              | {
                  tone?: ('signal' | 'amber' | 'teal' | 'ink') | null;
                  icon?: string | null;
                  site: string;
                  title: string;
                  detail?: string | null;
                  time?: string | null;
                  id?: string | null;
                }[]
              | null;
            aiInsightTitle?: string | null;
            aiInsightBody?: string | null;
            kpis?:
              | {
                  label: string;
                  value: string;
                  delta?: string | null;
                  deltaDirection?: ('up' | 'down') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            label?: string | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logos';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            cards?:
              | {
                  metric: string;
                  label: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'problem';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            steps?:
              | {
                  step: number;
                  icon?: string | null;
                  title: string;
                  description: string;
                  mockType: 'url' | 'insight' | 'alerts';
                  mockText?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'how-it-works';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            intro?: string | null;
            bullets?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            demoTitle?: string | null;
            demoBadge?: string | null;
            demoSite?: string | null;
            demoChange?: string | null;
            demoAnalysis?: string | null;
            demoActions?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Legacy card layout — leave empty when using bullets/demo
             */
            cards?:
              | {
                  title: string;
                  description: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            tabs?:
              | {
                  label: string;
                  items?:
                    | {
                        title: string;
                        body?: string | null;
                        image?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ai-intelligence';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'insights';
          }
        | {
            compactMode?: boolean | null;
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  realWin?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industries';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            columns?:
              | {
                  name: string;
                  isUs?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            rows?:
              | {
                  feature: string;
                  cells?:
                    | {
                        state?: ('yes' | 'no' | 'partial') | null;
                        note?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            /**
             * Select plans to display. Drag to reorder. Edit a plan record to update it everywhere it appears.
             */
            plans?: (number | Plan)[] | null;
            guaranteeNote?: string | null;
            billing?: {
              /**
               * Default: "Monthly"
               */
              monthlyLabel?: string | null;
              /**
               * Default: "Annual"
               */
              annualLabel?: string | null;
              /**
               * Default: "2 months free"
               */
              annualBadge?: string | null;
              /**
               * Default: "Billed annually · 2 months free"
               */
              annualNote?: string | null;
            };
            /**
             * Default: "Compare plans"
             */
            comparePlansHeadline?: string | null;
            /**
             * Default: "Features:"
             */
            featuresLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subheadline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            subtext?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            riskNote?: string | null;
            variant?: ('primary' | 'secondary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            image: number | Media;
            caption?: string | null;
            size?: ('full' | 'contained') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pricing plans. Referenced from the landing pricing block and the pricing page. Edit once, both pages update.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  price: string;
  period?: string | null;
  tagline?: string | null;
  features?:
    | {
        text?: string | null;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Annual price (e.g. "$16"). Leave blank to hide toggle.
   */
  priceAnnual?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  highlighted?: boolean | null;
  popularBadge?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface BlockLibrary {
  id: number;
  name: string;
  block?: { blockType: string; id?: string | null; [k: string]: unknown }[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: string | null;
  category?: ('Product' | 'Company' | 'Guide') | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrowBadge?: T;
              eyebrowText?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              trustLine?: T;
              image?: T;
              dashboardAlerts?:
                | T
                | {
                    tone?: T;
                    icon?: T;
                    site?: T;
                    title?: T;
                    detail?: T;
                    time?: T;
                    id?: T;
                  };
              aiInsightTitle?: T;
              aiInsightBody?: T;
              kpis?:
                | T
                | {
                    label?: T;
                    value?: T;
                    delta?: T;
                    deltaDirection?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logos?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        problem?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              cards?:
                | T
                | {
                    metric?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'how-it-works'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              steps?:
                | T
                | {
                    step?: T;
                    icon?: T;
                    title?: T;
                    description?: T;
                    mockType?: T;
                    mockText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              intro?: T;
              bullets?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              demoTitle?: T;
              demoBadge?: T;
              demoSite?: T;
              demoChange?: T;
              demoAnalysis?: T;
              demoActions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'ai-intelligence'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          title?: T;
                          body?: T;
                          image?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        insights?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        industries?:
          | T
          | {
              compactMode?: T;
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    realWin?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              columns?:
                | T
                | {
                    name?: T;
                    isUs?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    feature?: T;
                    cells?:
                      | T
                      | {
                          state?: T;
                          note?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              plans?: T;
              guaranteeNote?: T;
              billing?:
                | T
                | {
                    monthlyLabel?: T;
                    annualLabel?: T;
                    annualBadge?: T;
                    annualNote?: T;
                  };
              comparePlansHeadline?: T;
              featuresLabel?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subtext?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              riskNote?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  category?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  period?: T;
  tagline?: T;
  features?:
    | T
    | {
        text?: T;
        included?: T;
        id?: T;
      };
  priceAnnual?: T;
  ctaLabel?: T;
  ctaHref?: T;
  highlighted?: T;
  popularBadge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  blocks?:
    | (
        | {
            eyebrowBadge?: string | null;
            eyebrowText?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            trustLine?: string | null;
            image?: (number | null) | Media;
            dashboardAlerts?:
              | {
                  tone?: ('signal' | 'amber' | 'teal' | 'ink') | null;
                  icon?: string | null;
                  site: string;
                  title: string;
                  detail?: string | null;
                  time?: string | null;
                  id?: string | null;
                }[]
              | null;
            aiInsightTitle?: string | null;
            aiInsightBody?: string | null;
            kpis?:
              | {
                  label: string;
                  value: string;
                  delta?: string | null;
                  deltaDirection?: ('up' | 'down') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            label?: string | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logos';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            cards?:
              | {
                  metric: string;
                  label: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'problem';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            steps?:
              | {
                  step: number;
                  icon?: string | null;
                  title: string;
                  description: string;
                  mockType: 'url' | 'insight' | 'alerts';
                  mockText?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'how-it-works';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            intro?: string | null;
            bullets?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            demoTitle?: string | null;
            demoBadge?: string | null;
            demoSite?: string | null;
            demoChange?: string | null;
            demoAnalysis?: string | null;
            demoActions?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Legacy card layout — leave empty when using bullets/demo
             */
            cards?:
              | {
                  title: string;
                  description: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            tabs?:
              | {
                  label: string;
                  items?:
                    | {
                        title: string;
                        body?: string | null;
                        image?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ai-intelligence';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'insights';
          }
        | {
            compactMode?: boolean | null;
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  realWin?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industries';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            columns?:
              | {
                  name: string;
                  isUs?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            rows?:
              | {
                  feature: string;
                  cells?:
                    | {
                        state?: ('yes' | 'no' | 'partial') | null;
                        note?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            headlineHighlight?: string | null;
            subheadline?: string | null;
            /**
             * Select plans to display. Drag to reorder. Edit a plan record to update it everywhere it appears.
             */
            plans?: (number | Plan)[] | null;
            guaranteeNote?: string | null;
            billing?: {
              /**
               * Default: "Monthly"
               */
              monthlyLabel?: string | null;
              /**
               * Default: "Annual"
               */
              annualLabel?: string | null;
              /**
               * Default: "2 months free"
               */
              annualBadge?: string | null;
              /**
               * Default: "Billed annually · 2 months free"
               */
              annualNote?: string | null;
            };
            /**
             * Default: "Compare plans"
             */
            comparePlansHeadline?: string | null;
            /**
             * Default: "Features:"
             */
            featuresLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subheadline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            headlineHighlight?: string | null;
            subtext?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            riskNote?: string | null;
            variant?: ('primary' | 'secondary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            image: number | Media;
            caption?: string | null;
            size?: ('full' | 'contained') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page".
 */
export interface PricingPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineHighlight?: string | null;
    subheadline?: string | null;
  };
  /**
   * Select plans to display. Drag to reorder. Edit a plan record to update it everywhere it appears.
   */
  plans?: (number | Plan)[] | null;
  guaranteeNote?: string | null;
  billing?: {
    /**
     * Default: "Monthly"
     */
    monthlyLabel?: string | null;
    /**
     * Default: "Annual"
     */
    annualLabel?: string | null;
    /**
     * Badge on Annual button. Default: "2 months free"
     */
    annualBadge?: string | null;
    /**
     * Per-card note when annual selected. Default: "Billed annually · 2 months free"
     */
    annualNote?: string | null;
  };
  /**
   * Comparison table heading. Default: "Compare plans"
   */
  comparePlansHeadline?: string | null;
  /**
   * Label above feature list on each card. Default: "Features:"
   */
  featuresLabel?: string | null;
  faq?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  logo?: (number | null) | Media;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  signinLabel?: string | null;
  signinHref?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  tagline?: string | null;
  groups?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'twitter' | 'linkedin' | 'github' | 'youtube' | 'other';
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit any color value. Leave empty to keep built-in defaults. Affects the landing page only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Default #f3f3f3
   */
  pageBg?: string | null;
  /**
   * Default #e7e7eb
   */
  pageBgAlt?: string | null;
  /**
   * Default #ffffff
   */
  cardBg?: string | null;
  /**
   * Default #29144c
   */
  darkSurface?: string | null;
  /**
   * Default #131313
   */
  inkPrimary?: string | null;
  /**
   * Default #444141
   */
  inkSecondary?: string | null;
  /**
   * Default #6A35E0
   */
  accentPrimary?: string | null;
  /**
   * Default #8b5cf6
   */
  accentMuted?: string | null;
  /**
   * Default #f59e0b
   */
  accentGold?: string | null;
  /**
   * Default #14b8a6
   */
  accentTeal?: string | null;
  /**
   * Default rgba(0,0,0,0.08)
   */
  border?: string | null;
  /**
   * Default rgba(0,0,0,0.16)
   */
  borderStrong?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrowBadge?: T;
              eyebrowText?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              trustLine?: T;
              image?: T;
              dashboardAlerts?:
                | T
                | {
                    tone?: T;
                    icon?: T;
                    site?: T;
                    title?: T;
                    detail?: T;
                    time?: T;
                    id?: T;
                  };
              aiInsightTitle?: T;
              aiInsightBody?: T;
              kpis?:
                | T
                | {
                    label?: T;
                    value?: T;
                    delta?: T;
                    deltaDirection?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logos?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        problem?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              cards?:
                | T
                | {
                    metric?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'how-it-works'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              steps?:
                | T
                | {
                    step?: T;
                    icon?: T;
                    title?: T;
                    description?: T;
                    mockType?: T;
                    mockText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              intro?: T;
              bullets?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              demoTitle?: T;
              demoBadge?: T;
              demoSite?: T;
              demoChange?: T;
              demoAnalysis?: T;
              demoActions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'ai-intelligence'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          title?: T;
                          body?: T;
                          image?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        insights?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        industries?:
          | T
          | {
              compactMode?: T;
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    realWin?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              columns?:
                | T
                | {
                    name?: T;
                    isUs?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    feature?: T;
                    cells?:
                      | T
                      | {
                          state?: T;
                          note?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subheadline?: T;
              plans?: T;
              guaranteeNote?: T;
              billing?:
                | T
                | {
                    monthlyLabel?: T;
                    annualLabel?: T;
                    annualBadge?: T;
                    annualNote?: T;
                  };
              comparePlansHeadline?: T;
              featuresLabel?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineHighlight?: T;
              subtext?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              riskNote?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page_select".
 */
export interface PricingPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineHighlight?: T;
        subheadline?: T;
      };
  plans?: T;
  guaranteeNote?: T;
  billing?:
    | T
    | {
        monthlyLabel?: T;
        annualLabel?: T;
        annualBadge?: T;
        annualNote?: T;
      };
  comparePlansHeadline?: T;
  featuresLabel?: T;
  faq?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  signinLabel?: T;
  signinHref?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  tagline?: T;
  groups?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  pageBg?: T;
  pageBgAlt?: T;
  cardBg?: T;
  darkSurface?: T;
  inkPrimary?: T;
  inkSecondary?: T;
  accentPrimary?: T;
  accentMuted?: T;
  accentGold?: T;
  accentTeal?: T;
  border?: T;
  borderStrong?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}