// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: organization.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Organization message for gRPC
type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain     string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	SchemaName    string                 `protobuf:"bytes,4,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *Organization) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *Organization) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Organization) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Organization) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateOrganizationRequest for gRPC
type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain     string                 `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *CreateOrganizationRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

// CreateOrganizationReply for gRPC
type CreateOrganizationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationReply) Reset() {
	*x = CreateOrganizationReply{}
	mi := &file_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationReply) ProtoMessage() {}

func (x *CreateOrganizationReply) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationReply.ProtoReflect.Descriptor instead.
func (*CreateOrganizationReply) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationReply) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

// GetOrganizationRequest for gRPC
type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetOrganizationReply for gRPC
type GetOrganizationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationReply) Reset() {
	*x = GetOrganizationReply{}
	mi := &file_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationReply) ProtoMessage() {}

func (x *GetOrganizationReply) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationReply.ProtoReflect.Descriptor instead.
func (*GetOrganizationReply) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrganizationReply) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

// GetOrganizationBySubdomainRequest for gRPC
type GetOrganizationBySubdomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subdomain     string                 `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationBySubdomainRequest) Reset() {
	*x = GetOrganizationBySubdomainRequest{}
	mi := &file_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationBySubdomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationBySubdomainRequest) ProtoMessage() {}

func (x *GetOrganizationBySubdomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationBySubdomainRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationBySubdomainRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrganizationBySubdomainRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

// GetOrganizationBySubdomainReply for gRPC
type GetOrganizationBySubdomainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationBySubdomainReply) Reset() {
	*x = GetOrganizationBySubdomainReply{}
	mi := &file_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationBySubdomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationBySubdomainReply) ProtoMessage() {}

func (x *GetOrganizationBySubdomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationBySubdomainReply.ProtoReflect.Descriptor instead.
func (*GetOrganizationBySubdomainReply) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrganizationBySubdomainReply) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

var File_organization_proto protoreflect.FileDescriptor

const file_organization_proto_rawDesc = "" +
	"\n" +
	"\x12organization.proto\x12\forganization\"\xd3\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12\x1f\n" +
	"\vschema_name\x18\x04 \x01(\tR\n" +
	"schemaName\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\tR\vownerUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"q\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tsubdomain\x18\x02 \x01(\tR\tsubdomain\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\"Y\n" +
	"\x17CreateOrganizationReply\x12>\n" +
	"\forganization\x18\x01 \x01(\v2\x1a.organization.OrganizationR\forganization\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x14GetOrganizationReply\x12>\n" +
	"\forganization\x18\x01 \x01(\v2\x1a.organization.OrganizationR\forganization\"A\n" +
	"!GetOrganizationBySubdomainRequest\x12\x1c\n" +
	"\tsubdomain\x18\x01 \x01(\tR\tsubdomain\"a\n" +
	"\x1fGetOrganizationBySubdomainReply\x12>\n" +
	"\forganization\x18\x01 \x01(\v2\x1a.organization.OrganizationR\forganization2\xd6\x02\n" +
	"\x13OrganizationService\x12d\n" +
	"\x12CreateOrganization\x12'.organization.CreateOrganizationRequest\x1a%.organization.CreateOrganizationReply\x12[\n" +
	"\x0fGetOrganization\x12$.organization.GetOrganizationRequest\x1a\".organization.GetOrganizationReply\x12|\n" +
	"\x1aGetOrganizationBySubdomain\x12/.organization.GetOrganizationBySubdomainRequest\x1a-.organization.GetOrganizationBySubdomainReplyBOZMgithub.com/jcsoftdev/pulzifi-back/modules/organization/infrastructure/grpc/pbb\x06proto3"

var (
	file_organization_proto_rawDescOnce sync.Once
	file_organization_proto_rawDescData []byte
)

func file_organization_proto_rawDescGZIP() []byte {
	file_organization_proto_rawDescOnce.Do(func() {
		file_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)))
	})
	return file_organization_proto_rawDescData
}

var file_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_organization_proto_goTypes = []any{
	(*Organization)(nil),                      // 0: organization.Organization
	(*CreateOrganizationRequest)(nil),         // 1: organization.CreateOrganizationRequest
	(*CreateOrganizationReply)(nil),           // 2: organization.CreateOrganizationReply
	(*GetOrganizationRequest)(nil),            // 3: organization.GetOrganizationRequest
	(*GetOrganizationReply)(nil),              // 4: organization.GetOrganizationReply
	(*GetOrganizationBySubdomainRequest)(nil), // 5: organization.GetOrganizationBySubdomainRequest
	(*GetOrganizationBySubdomainReply)(nil),   // 6: organization.GetOrganizationBySubdomainReply
}
var file_organization_proto_depIdxs = []int32{
	0, // 0: organization.CreateOrganizationReply.organization:type_name -> organization.Organization
	0, // 1: organization.GetOrganizationReply.organization:type_name -> organization.Organization
	0, // 2: organization.GetOrganizationBySubdomainReply.organization:type_name -> organization.Organization
	1, // 3: organization.OrganizationService.CreateOrganization:input_type -> organization.CreateOrganizationRequest
	3, // 4: organization.OrganizationService.GetOrganization:input_type -> organization.GetOrganizationRequest
	5, // 5: organization.OrganizationService.GetOrganizationBySubdomain:input_type -> organization.GetOrganizationBySubdomainRequest
	2, // 6: organization.OrganizationService.CreateOrganization:output_type -> organization.CreateOrganizationReply
	4, // 7: organization.OrganizationService.GetOrganization:output_type -> organization.GetOrganizationReply
	6, // 8: organization.OrganizationService.GetOrganizationBySubdomain:output_type -> organization.GetOrganizationBySubdomainReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_organization_proto_init() }
func file_organization_proto_init() {
	if File_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_proto_goTypes,
		DependencyIndexes: file_organization_proto_depIdxs,
		MessageInfos:      file_organization_proto_msgTypes,
	}.Build()
	File_organization_proto = out.File
	file_organization_proto_goTypes = nil
	file_organization_proto_depIdxs = nil
}
