import type { Page } from "patchright";
import type { PreviewElement } from "../../domain/entities/preview-result";

/**
 * Maps visible page sections to PreviewElement objects using a
 * depth-controlled DOM walk — designed for change detection, not
 * fine-grained element targeting.
 *
 * @param page       Playwright page (scrolled to top, render-stable)
 * @param maxDepth   How many levels of *meaningful* sections to descend.
 *                   1 = top-level regions only (header, main, footer, …)
 *                   2 = subsections within those (default)
 *                   3 = one more level of nesting
 *                   Wrapper divs are transparent and don't consume depth.
 */
export async function mapSemanticElements(
  page: Page,
  maxDepth = 3,
): Promise<PreviewElement[]> {
  return page.evaluate((maxDepth: number) => {
    // ────────────── Constants ──────────────

    const SEMANTIC_SECTIONS = new Set([
      "header",
      "nav",
      "main",
      "article",
      "section",
      "aside",
      "footer",
      "form",
    ]);

    const TAG_ROLES: Record<string, string> = {
      header: "header",
      nav: "navigation",
      main: "main",
      article: "article",
      section: "section",
      aside: "complementary",
      footer: "footer",
      form: "form",
      h1: "heading",
      h2: "heading",
      h3: "heading",
      h4: "heading",
      h5: "heading",
      h6: "heading",
      img: "image",
      video: "media",
      audio: "media",
      table: "table",
      ul: "list",
      ol: "list",
    };

    const ARIA_ROLE_MAP: Record<string, string> = {
      banner: "header",
      navigation: "navigation",
      main: "main",
      complementary: "complementary",
      contentinfo: "footer",
      form: "form",
      search: "search",
      region: "section",
      article: "article",
      dialog: "dialog",
      alertdialog: "dialog",
      tabpanel: "section",
    };

    const SKIP_TAGS = new Set([
      "script",
      "style",
      "link",
      "meta",
      "noscript",
      "br",
      "hr",
      "svg",
      "path",
      "head",
      "template",
      "iframe",
    ]);

    const UTILITY_RE =
      /^(flex|grid|block|inline|hidden|visible|relative|absolute|fixed|sticky|overflow|z-|w-|h-|p[xytblr]?-|m[xytblr]?-|bg-|text-|border-|rounded|shadow|opacity|transition|transform|cursor|pointer|select-|sr-|dark:|hover:|focus:|sm:|md:|lg:|xl:|2xl:|min-|max-|gap-|space-|items-|justify-|self-|col-|row-|order-|float-|clear-|object-|aspect-|container$|font-|leading-|tracking-|whitespace-|break-|decoration-|underline|line-through|no-underline|uppercase|lowercase|capitalize|truncate|align-|table-|group$|peer$|animate-|ring-|outline-|placeholder-|accent-|caret-|scroll-|snap-|touch-|resize|appearance-|columns-|place-|basis-|grow|shrink|backdrop-|will-|content-|forced-|divide-|not-|only-|first:|last:|odd:|even:|visited:|disabled:|checked:|empty:|enabled:)/;

    // Min size per depth level (deeper = allow smaller)
    const MIN_SIZE_BY_DEPTH = [
      { w: 150, h: 50 },  // depth 0 — top-level regions
      { w: 80, h: 35 },   // depth 1
      { w: 50, h: 25 },   // depth 2
      { w: 30, h: 15 },   // depth 3+
    ];

    // Absolute DOM depth limit to avoid infinite wrapper recursion
    const MAX_DOM_DEPTH = 25;

    // ────────────── Helpers ──────────────

    function isAutoGeneratedId(id: string): boolean {
      if (/^[0-9a-f]{8,}$/i.test(id)) return true;
      if (/^[a-z]+-[0-9a-f]{4,}/i.test(id)) return true;
      if (/^\d+$/.test(id)) return true;
      if (/^:r[0-9a-z]+:$/i.test(id)) return true;
      if (/^(radix|react|rc|mui|headless|__next)-/.test(id)) return true;
      return false;
    }

    function getMeaningfulClasses(el: Element): string[] {
      return Array.from(el.classList).filter((cls) => {
        if (cls.length < 3) return false;
        if (UTILITY_RE.test(cls)) return false;
        return true;
      });
    }

    function hasMeaningfulAttributes(el: Element): boolean {
      if (el.id && !isAutoGeneratedId(el.id)) return true;
      if (el.getAttribute("role")) return true;
      for (const attr of [
        "data-testid",
        "data-test-id",
        "data-cy",
        "data-section",
        "data-component",
        "data-block",
        "data-id",
      ]) {
        if (el.hasAttribute(attr)) return true;
      }
      if (el.getAttribute("aria-label")) return true;
      return false;
    }

    /**
     * Checks if an element qualifies as a "section" — a meaningful
     * page region worth monitoring for changes.
     *
     * A tall element (height >= 3× the depth minimum) is always
     * considered a section — large visual regions are meaningful
     * for comparison even without semantic markup or special classes.
     */
    function isSectionCandidate(el: Element, minW: number, minH: number): boolean {
      const tag = el.tagName.toLowerCase();
      if (SKIP_TAGS.has(tag)) return false;

      const rect = el.getBoundingClientRect();
      if (rect.width < minW || rect.height < minH) return false;
      if (rect.bottom < 0 || rect.right < 0) return false;

      // Semantic section tags are always candidates
      if (SEMANTIC_SECTIONS.has(tag)) return true;

      // Elements with meaningful attributes
      if (hasMeaningfulAttributes(el)) return true;

      // Tall elements are meaningful page regions regardless of attributes.
      // Threshold scales with depth level (3× the min height at this depth).
      if (rect.height >= minH * 3) return true;

      // Divs/spans with at least one meaningful class name
      if (tag === "div" || tag === "span") {
        return getMeaningfulClasses(el).length > 0;
      }

      return false;
    }

    /**
     * Checks if an element is a transparent wrapper — just nesting,
     * no semantic meaning. We recurse through these without consuming depth.
     *
     * Tall elements are never transparent — they represent visible
     * page regions even without semantic attributes.
     */
    function isTransparentWrapper(el: Element, minH: number): boolean {
      const tag = el.tagName.toLowerCase();
      if (tag !== "div" && tag !== "span") return false;
      if (hasMeaningfulAttributes(el)) return false;
      if (getMeaningfulClasses(el).length > 0) return false;

      // A tall element is a real section, not a wrapper
      const rect = el.getBoundingClientRect();
      if (rect.height >= minH * 3) return false;

      // Must have at least one element child (not a leaf)
      return el.children.length > 0;
    }

    // ────────────── Selector generation ──────────────

    const MAX_SELECTOR_DEPTH = 4;

    function getCssSelector(el: Element, depth = 0): string {
      if (el.id && !isAutoGeneratedId(el.id)) {
        return `#${CSS.escape(el.id)}`;
      }

      for (const attr of [
        "data-testid",
        "data-test-id",
        "data-cy",
        "data-section",
        "data-component",
      ]) {
        const val = el.getAttribute(attr);
        if (val) return `[${attr}="${CSS.escape(val)}"]`;
      }

      const tag = el.tagName.toLowerCase();

      const role = el.getAttribute("role");
      if (role) {
        const sel = `${tag}[role="${role}"]`;
        try {
          if (document.querySelectorAll(sel).length === 1) return sel;
        } catch {}
      }

      const classes = getMeaningfulClasses(el);
      if (classes.length > 0) {
        for (const cls of classes) {
          try {
            const sel = `.${CSS.escape(cls)}`;
            if (document.querySelectorAll(sel).length === 1) return sel;
          } catch {}
        }
        for (const cls of classes) {
          try {
            const sel = `${tag}.${CSS.escape(cls)}`;
            if (document.querySelectorAll(sel).length === 1) return sel;
          } catch {}
        }
        if (classes.length >= 2) {
          const limit = Math.min(classes.length, 4);
          for (let i = 0; i < limit; i++) {
            for (let j = i + 1; j < limit; j++) {
              try {
                const sel = `.${CSS.escape(classes[i])}.${CSS.escape(classes[j])}`;
                if (document.querySelectorAll(sel).length === 1) return sel;
              } catch {}
            }
          }
        }
      }

      // Fallback — parent chain
      if (depth >= MAX_SELECTOR_DEPTH) {
        if (classes.length > 0)
          return `${tag}.${classes.map((c) => CSS.escape(c)).join(".")}`;
        return tag;
      }

      const parent = el.parentElement;
      if (!parent || parent === document.documentElement) return tag;

      const siblings = Array.from(parent.children).filter(
        (s) => s.tagName === el.tagName,
      );
      if (siblings.length === 1)
        return `${getCssSelector(parent, depth + 1)} > ${tag}`;
      const index = siblings.indexOf(el) + 1;
      return `${getCssSelector(parent, depth + 1)} > ${tag}:nth-of-type(${index})`;
    }

    function getXPath(el: Element): string {
      if (el.id && !isAutoGeneratedId(el.id))
        return `//*[@id="${el.id}"]`;

      const parts: string[] = [];
      let current: Element | null = el;
      while (current && current !== document.documentElement) {
        const tag = current.tagName.toLowerCase();
        const parentEl: Element | null = current.parentElement;
        if (parentEl) {
          const siblings = Array.from(parentEl.children).filter(
            (s: Element) => s.tagName === current!.tagName,
          );
          if (siblings.length > 1) {
            const idx = siblings.indexOf(current) + 1;
            parts.unshift(`${tag}[${idx}]`);
          } else {
            parts.unshift(tag);
          }
        } else {
          parts.unshift(tag);
        }
        current = parentEl;
      }
      return "/" + parts.join("/");
    }

    function getRole(el: Element): string {
      const ariaRole = el.getAttribute("role");
      if (ariaRole && ARIA_ROLE_MAP[ariaRole]) return ARIA_ROLE_MAP[ariaRole];
      if (ariaRole) return ariaRole;
      const tag = el.tagName.toLowerCase();
      return TAG_ROLES[tag] || "generic";
    }

    // ────────────── Depth-based DOM walk ──────────────

    type Candidate = {
      el: Element;
      sectionDepth: number; // which meaningful depth level it was found at
    };

    /**
     * Walks the DOM from `parent` downward, collecting section candidates.
     *
     * - sectionDepth tracks how many levels of *meaningful sections* we've
     *   descended through (transparent wrappers don't count).
     * - domDepth tracks raw DOM nesting to prevent runaway recursion.
     */
    function discoverSections(
      parent: Element,
      sectionDepth: number,
      domDepth: number,
    ): Candidate[] {
      if (sectionDepth >= maxDepth || domDepth >= MAX_DOM_DEPTH) return [];

      const minSize =
        MIN_SIZE_BY_DEPTH[Math.min(sectionDepth, MIN_SIZE_BY_DEPTH.length - 1)];
      const results: Candidate[] = [];

      for (const child of Array.from(parent.children)) {
        const tag = child.tagName.toLowerCase();
        if (SKIP_TAGS.has(tag)) continue;

        if (isSectionCandidate(child, minSize.w, minSize.h)) {
          results.push({ el: child, sectionDepth });
          // Recurse into this section for subsections (consumes depth)
          results.push(
            ...discoverSections(child, sectionDepth + 1, domDepth + 1),
          );
        } else if (isTransparentWrapper(child, minSize.h)) {
          // Skip through wrapper without consuming section depth
          results.push(
            ...discoverSections(child, sectionDepth, domDepth + 1),
          );
        }
      }

      return results;
    }

    // ────────────── Run discovery ──────────────

    const candidates = discoverSections(document.body, 0, 0);

    // ────────────── Build results ──────────────

    type Result = {
      selector: string;
      xpath: string;
      tag: string;
      rect: { x: number; y: number; w: number; h: number };
      text_preview: string;
      semantic_role: string;
    };

    const results: Result[] = [];

    for (const { el } of candidates) {
      const rect = el.getBoundingClientRect();
      const tag = el.tagName.toLowerCase();
      const role = getRole(el);

      const textContent = (el.textContent || "").trim();
      const textPreview =
        textContent.length > 100
          ? textContent.substring(0, 100) + "..."
          : textContent;

      results.push({
        selector: getCssSelector(el),
        xpath: getXPath(el),
        tag,
        rect: {
          x: Math.round(rect.x),
          y: Math.round(rect.y),
          w: Math.round(rect.width),
          h: Math.round(rect.height),
        },
        text_preview: textPreview,
        semantic_role: role,
      });
    }

    // ────────────── Deduplicate near-identical bounds ──────────────

    const deduplicated = results.filter((a, i) => {
      for (let j = 0; j < results.length; j++) {
        if (i === j) continue;
        const b = results[j];
        const aContainsB =
          a.rect.x <= b.rect.x &&
          a.rect.y <= b.rect.y &&
          a.rect.x + a.rect.w >= b.rect.x + b.rect.w &&
          a.rect.y + a.rect.h >= b.rect.y + b.rect.h;

        if (aContainsB) {
          const dx = Math.abs(a.rect.x - b.rect.x);
          const dy = Math.abs(a.rect.y - b.rect.y);
          const dw = Math.abs(a.rect.w - b.rect.w);
          const dh = Math.abs(a.rect.h - b.rect.h);
          if (dx < 20 && dy < 20 && dw < 40 && dh < 40) {
            return false; // remove outer element
          }
        }
      }
      return true;
    });

    // ────────────── Sort by position ──────────────

    deduplicated.sort((a, b) => {
      if (Math.abs(a.rect.y - b.rect.y) > 20) return a.rect.y - b.rect.y;
      if (Math.abs(a.rect.x - b.rect.x) > 20) return a.rect.x - b.rect.x;
      return b.rect.w * b.rect.h - (a.rect.w * a.rect.h);
    });

    return deduplicated;
  }, maxDepth);
}
